import type { Project } from "@/types/project";

export const FEATURED_PROJECTS: Project[] = [

  {
    slug: "obeetee",
    title: "OBEETEE",
    category: "Brand",
    tagline: "Luxury handcrafted rug brand",
    year: "2024",
    client: "Client",
    heroVideo: "/obeetee/Obeetee.mp4",
    poster: "/obeetee/obeetee.webp",
    overview: "OBEETEE is a luxury handcrafted rug brand known for blending traditional Indian craftsmanship with contemporary design.",
    gallery: [
      "/obeetee/obeetee1.webp",
      "/obeetee/obeetee2.webp",
      "/obeetee/obeetee3.webp",
    ],
    bts: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1600&q=80",
    ],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "2:45", format: "4K" },
    featured: true,
    order: 1,
  },
  {
    slug: "twiddles",
    title: "Twiddles",
    category: "Brand",
    tagline: "Modern snack brand",
    year: "2024",
    client: "Brand",
    heroVideo: "/twiddles/Twiddles.mp4",
    poster: "/twiddles/twiddles.webp",
    overview: "Twiddles is a modern snack brand co-founded by Yuvraj Singh, focused on creating healthier and more mindful snacking alternatives.\n\nWith strong branding and a youthful identity, Twiddles stands out through its fresh visual language and modern consumer appeal.",
    gallery: [
      "/twiddles/twiddles-04.webp",
      "/twiddles/twiddles-24.webp",
    ],
    bts: [],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "1:15", format: "4K" },
    featured: false,
    order: 6,
  },
  {
    slug: "kubra-sait",
    title: "Kubra Sait",
    category: "Actress",
    tagline: "Actress and performer",
    year: "2024",
    client: "Client",
    heroVideo: "/kubra/Kubra.mp4",
    poster: "/kubra/kubra-sait.webp",
    overview: "Kubra Sait is an actress, host, and performer known for her bold screen presence, versatility, and strong individuality within the industry.\n\nWith a distinct personality and contemporary creative presence, Kubra represents a powerful blend of storytelling, charisma, and talent.",
    gallery: [
      "/kubra/_dsc4524.webp",
      "/kubra/_dsc4561.webp",
    ],
    bts: [],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "2:15", format: "4K" },
    featured: false,
    order: 9,
  },
  {
    slug: "ashna-suri",
    title: "Ashna Suri",
    category: "Creator",
    tagline: "Digital creator",
    year: "2024",
    client: "Client",
    heroVideo: "/ashna-suri/Ashna.mp4",
    poster: "/ashna-suri/ashna-suri.webp",
    overview: "Ashna Suri is a digital creator known for her elegant visual presence, lifestyle-driven storytelling, and contemporary fashion sense.\n\nSanat Arora has been creatively collaborating with Ashna for more than 4 years, building a strong visual language together.",
    gallery: [
      "/ashna-suri/_dsc4776.webp",
      "/ashna-suri/_dsc4827.webp",
    ],
    bts: [],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "1:45", format: "4K" },
    featured: false,
    order: 4,
  },
  {
    slug: "ravya-arora",
    title: "Ravya Arora",
    category: "Creator",
    tagline: "Creative collaboration",
    year: "2024",
    client: "Client",
    heroVideo: "/Zomato.mp4",
    poster: "/ravya.webp",
    overview: "Sanat Arora and Ravya Arora share a long-standing creative collaboration built on storytelling, visual identity, and artistic vision.\n\nWith Sanat's cinematic eye and deep passion for the art of filmmaking, combined with Ravya's strong digital presence and influence.",
    gallery: [
      "https://images.unsplash.com/photo-1618005198919-d0d4f0a9d0e0?w=1600&q=80",
    ],
    bts: [],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "1:30", format: "4K" },
    featured: true,
    order: 2,
  },
  {
    slug: "adeboy",
    title: "Adeboy",
    category: "Fashion Brand",
    tagline: "Modern footwear brand",
    year: "2024",
    client: "Client",
    heroVideo: "/Adeboy Combined 2.mp4",
    poster: "/adeboy.webp",
    overview: "Adeboy is a modern footwear brand focused on combining contemporary streetwear aesthetics with everyday comfort and utility.\n\nBuilt for a generation that values both style and identity, Adeboy reflects confidence, creativity, and the evolving culture of fashion.",
    gallery: [
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&q=80",
    ],
    bts: [],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "1:00", format: "4K" },
    featured: false,
    order: 3,
  },
  {
    slug: "pronto",
    title: "Pronto",
    category: "Brand",
    tagline: "Modern cleaning services",
    year: "2024",
    client: "Client",
    heroVideo: "/Pronto.mp4",
    poster: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1b4?w=1920&q=80",
    overview: "Pronto is a modern cleaning services brand focused on delivering reliable, efficient, and professional solutions with a fresh approach.\n\nSanat Arora and his team were behind Pronto's first-ever advertisement shoot, helping shape the brand's initial visual identity.",
    gallery: [
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&q=80",
    ],
    bts: [],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "0:45", format: "4K" },
    featured: true,
    order: 5,
  },
  {
    slug: "fratelli-wines",
    title: "Fratelli Wines",
    category: "Brand",
    tagline: "Premium wine brand",
    year: "2024",
    client: "Brand",
    heroVideo: "/Fratelli.mp4",
    poster: "https://images.unsplash.com/photo-1478720568477-152d9b164e63?w=1920&q=80",
    overview: "Fratelli Wines is one of India's leading premium wine brands, known for combining international winemaking expertise with Indian terroir.\n\nRepresenting elegance, culture, and elevated experiences, Fratelli Wines stands as a symbol of modern Indian luxury with global appeal.",
    gallery: [
      "https://images.unsplash.com/photo-1485846232355-8c050e260f0f?w=1600&q=80",
    ],
    bts: [],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "2:00", format: "4K" },
    featured: true,
    order: 7,
  },
  {
    slug: "novora",
    title: "Novora",
    category: "Brand",
    tagline: "Modern activewear scrubs",
    year: "2024",
    client: "Brand",
    heroVideo: "/novora/Novora.mp4",
    poster: "/novora/novora.webp",
    overview: "Novora is a modern activewear scrubs brand designed for doctors and healthcare professionals who value both comfort and style.\n\nBuilt around movement, confidence, and modern medical culture, Novora brings a fresh and elevated approach to healthcare apparel.",
    gallery: [
      "/novora/novora-18.webp",
    ],
    bts: [],
    production: { director: "Sanat Arora", cinematography: "Sanat Arora", edit: "91-11 Post", duration: "1:00", format: "4K" },
    featured: false,
    order: 8,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return FEATURED_PROJECTS.find((p) => p.slug === slug);
}

export function getAllProjectSlugs(): string[] {
  return FEATURED_PROJECTS.map((p) => p.slug);
}
